In [1]:
import torch
from matplotlib import pyplot as plt

from hysteresis.base import BaseHysteresis
from hysteresis.reconstruction import reconstruction
from hysteresis.visualization import plot_hysterion_density
from hysteresis.training import train_hysteresis

train_h = torch.linspace(0, 20, 100)
train_h = torch.cat((train_h, train_h.flipud()))
train_m = 2.0 * train_h
H = BaseHysteresis(train_h, train_m, mesh_scale=0.5)

0


In [2]:
train_hysteresis(H, 1000)

0


tensor([1.0661e+00, 2.3120e+04, 1.5129e+03, 4.9259e+03, 1.3301e+04, 1.0108e+04,
        2.9347e+03, 9.3882e+00, 2.7556e+03, 6.2545e+03, 6.1764e+03, 3.1787e+03,
        4.6472e+02, 2.4274e+02, 2.0110e+03, 3.4695e+03, 3.1084e+03, 1.4699e+03,
        1.5900e+02, 1.9869e+02, 1.1960e+03, 1.9205e+03, 1.6319e+03, 6.9977e+02,
        4.4120e+01, 1.7499e+02, 7.6394e+02, 1.0885e+03, 8.1618e+02, 2.7102e+02,
        5.6202e-01, 1.9075e+02, 5.2885e+02, 6.0205e+02, 3.4640e+02, 5.7994e+01,
        2.2279e+01, 2.1004e+02, 3.5580e+02, 2.8553e+02, 9.4936e+01, 2.5336e-02,
        7.5655e+01, 1.9181e+02, 1.9443e+02, 8.7749e+01, 4.1905e+00, 2.8235e+01,
        1.0340e+02, 1.2195e+02, 6.3385e+01, 5.4911e+00, 1.2989e+01, 5.9314e+01,
        7.4270e+01, 3.9491e+01, 3.3791e+00, 8.3570e+00, 3.7084e+01, 4.4590e+01,
        2.1635e+01, 1.0359e+00, 7.2054e+00, 2.4818e+01, 2.5948e+01, 1.0008e+01,
        2.9387e-02, 7.0838e+00, 1.6910e+01, 1.3961e+01, 3.4184e+00, 4.1532e-01,
        6.8727e+00, 1.0953e+01, 6.3644e+

In [3]:
print(H.transformer.scale_m)
print(H.offset)
print(H.slope)
print(H.scale)

tensor(0.0012)
tensor([0.5353], grad_fn=<AddBackward0>)
tensor([-1.0490], grad_fn=<AddBackward0>)
tensor([0.5022], grad_fn=<AddBackward0>)


In [4]:
H_reconstruct = reconstruction(H)
print(H_reconstruct.offset)
print(H_reconstruct.slope)
print(H_reconstruct.scale)

tensor(18.9810, dtype=torch.float64, grad_fn=<SumBackward0>)
tensor([0.0024], grad_fn=<AddBackward0>)
tensor([0.], grad_fn=<AddBackward0>)
tensor([91.1358], grad_fn=<AddBackward0>)
